services:
  postgres:
    container_name: nest-clean-ph
    image: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest-clean
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
  postgres-test:
    container_name: nest-clean-test-e2e
    image: postgres
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
      PGDATA: /data/test
    tmpfs:
      - /var/lib/postgresql/data