services:
  postgres:
    container_name: nest-clean-ph
    image: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest-clean
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
